### ISSUE TITLE
Share visualization button missing

### ISSUE THREAD

**Issue by cBevilaqua** [awslabs/amazon-quicksight-embedding-sdk#120]
In a previous moment, using the embed console, I can see a button named "Share this Visualization" that opened a modal window with a sharable link that I used to copy the dashboard ID from.
Now, there are only 2 options "Share Panel" and "Report by Email".
Is there any special setting to show the "Share this Visualization" button? Or it was removed from Quicksight Embedding sdk?
Thanks.

**Comment by Dhairyasarous** [comment]
Can you provide screenshots of a dashboard (please make sure that the data is not confidential) and the buttons you expect to show? We are not sure what you mean by "Share Panel", "Report by Email" and "Share this Visualization".

**Comment by cBevilaqua** [comment]
Here are the screenshots, the first one is the dashboard in official Quicksight web UI, you can see the "Share this visualization (Compartilhar esta visualização)", although, in the other screenshot that is from Quicksight embedded SDK, we can't see this option anymore.

![qs_original](https://user-images.githubusercontent.com/5955679/178080057-62d28cbf-cebe-41c3-8e2d-242810eef605.png)
![qs_embedded](https://user-images.githubusercontent.com/5955679/178080068-87681c68-c6cb-4f2b-8ebc-d1ae061097f1.png)

Thanks!

**Comment by sonals-amazon** [comment]
@cBevilaqua The feature you are referring to is actually "Share this View" which would let you share the exact same view with other users. On clicking on this button you would get a QuickSight website url. This feature was disabled for Embedding because the link generated with this feature is a QuickSight link which embedding customers cannot use. Were you using this feature before it was disabled(for embedding)? If so, how?

**Comment by sonals-amazon** [comment]
I see. I will mark this issue as closed in that case.
