### ISSUE TITLE
Hyphen(-) in the url is making the embedded url incorrect 

### ISSUE THREAD

**Issue by suryasr007** [awslabs/amazon-quicksight-embedding-sdk#126]
![image](https://user-images.githubusercontent.com/10533926/191978209-0388a7fb-3d71-45e1-9f7b-0018dda8a18d.png)

The Hyphen in the url after `punyCodeEmbedOrigin` parameter is causing issues.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/10533926/191978799-ca5b13b7-1aa9-41a4-a4b1-f73f1692a234.png">

 As soon as I remove the remove Hyphen, the iframe loads without any issues.

**Comment by sonals-amazon** [comment]
We are not able to reproduce the issue and the "-" is present in the punyCodeOrigin for all requests and is not a problem.
 
We will need more information to help debug this issue i.e. see all the parameters in the request including authCode. Github is not the right medium to get this confidential information. Can you open an AWS Support case so that we can work in a private forum.

**Comment by suryasr007** [comment]
Thanks for the info.
