### ISSUE TITLE
Multiple iframes inserted

### ISSUE THREAD

**Issue by joshuablokland** [awslabs/amazon-quicksight-embedding-sdk#153]
We are using this package to display QuickSight dashboards inside of a React application. The dashboard url is requested before embedding them with this package into our application. In our navigation structure we pick up the necessary parameters, generate a dashboard url and then embed it into a `div`.

The problem that we are facing is whenever we create a new dashboard url when the navigation changes it just embeds another iframe and it keeps stacking up. Right now we are manually removing these iframe's through JavaScript but this is not the "React way".

Is there a possibility that we do a check if there are existing iframe's and remove them in this package?
Or maybe even better, create a React component that renders a dashboard by dashboard url, and optional parameters?

**Comment by bwelkin** [comment]
Do you mean you see multiple embedded dashboards in your embedding container `div`?

If so, since the embedding dashboard iframe is created independent from React, removing it will not be "React way" either. However, your React application should have control on the rendering of the iframe's container. You could dynamically create the container for the iframe just before populating `frameOptions` and assign it's reference to `frameOptions.container`. Removing that container "React way" implicitly removes it's child iframe.

Embedding SDK 2.x also creates a control frame as the last child of the `body`. If it is also stacking up, make sure that you create the embedding context only once in your application.

**Comment by HanojHanu** [comment]
yes same here.. any fix available ?

**Comment by leftclickben** [comment]
Here's a simplified version (minus parameters like width, height, etc) of a solution I'm using:

```
export const EmbeddedDashboard = ({ url, parameters, index }) => {
  useEffect(() => {
    const embedDashboard = async () => {
      const embeddingContext = await createEmbeddingContext()
      await embeddingContext.embedVisual(
        {
          url,
          container: `#qs-visual-container-${index}`
        },
        {
          parameters
        }
      );
    };
    embedDashboard()
  }, [url, parameters.length])

  return (
    <div id={`qs-visual-container-${index}`}></div>
  )
}
```

The `EmbeddedDashboard` component renders a `div` with a unique `id`, and then embeds the visual into that `div`. When the `EmbeddedDashboard`  is removed from its parent, that includes both the `div` and the embedded `iframe`.

Note the list of dependencies for `useEffect()`. It doesn't work if you specify the full list of deps (`[url, parameters, index]`). I'm not sure why, it's been a while since I have used React and working is good enough for me :-)  You might need to disable a warning from your linter.

**Comment by HanojHanu** [comment]
For me, In local problem is

```jsx
root.render(
 //  <StrictMode>
    <App />
 // </StrictMode>
);
```

**Comment by sonals-amazon** [comment]
@HanojHanu StrictMode renders the component twice when you are in `development` mode. See react's documentation for details - https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development

You can disable `StrictMode` and the problem should be fixed.

**Comment by Wild-Soul** [comment]
There should Ideally be an unmount of terminate method in DashboardExperience to make things simpler.
