### ISSUE TITLE
aws quicksight dashboard embed url expiring after 5 minutes even after embeding in whitelist domain

### ISSUE THREAD

**Issue by ethdev279** [awslabs/amazon-quicksight-embedding-sdk#52]
when I try to embed dashboard URL to my website, it is becoming invalid after 5 minutes even I set --session-lifetime-in-minutes to max value ie 600. is this behavior normal? how to increase validity dashboard embed URL session up to 10 hrs as they said in docs

Reference: https://docs.aws.amazon.com/cli/latest/reference/quicksight/get-dashboard-embed-url.html?highlight=quicksight

**Comment by Pythonen** [comment]
Could you elaborate how did you deal with this?

**Comment by ferealqq** [comment]
How did you fix this issue?

**Comment by Salmandabbakuti** [comment]
I've created a lambda function that fetches new embed url when we hit it. So in webapp, whenever we refresh the page it will call the lambda function to fetch new url and embeding that in the app. That is the workaround I found for now.

**Comment by ethdev279** [comment]
I've created a lambda function that fetches new embed url when we hit it. So in web app, whenever we refresh the page it will call the lambda function to fetch new url and embeding that in the app. That is the workaround I found for now.

**Comment by ferealqq** [comment]
So if I understand correctly the "30 minute" embedding session starts when you ask the lamda function for the first time? And if the same reader asks for another embedding URL within 30 minutes the Quicksight API does not create a new session and charge another $0.30? 

https://aws.amazon.com/quicksight/pricing/

**Comment by sairayapureddy** [comment]
Any update on the fix for this issue?

I think there should be a better way to use the session optimally. Generally when we embed dashboards in a web page, it is not guaranteed that a user will remain on the same page for the entire session duration. Whenever he navigates to a new page and comes back to dashboard fetching a new embed url seems like it is requesting a new session altogether.

Is this because the user pricing is capped at $5 per month irrespective of number of sessions he uses?

**What does the $5/mo. max on reader charges (when billed using per user model) mean?**

Readers are charged at $0.30/session for the first 16 sessions in a calendar month. The 17th session in the month is charged at $0.20/session, after which there are no more charges for the month. **The reader has unlimited access to QuickSight for $5 charge accrued from the first 17 sessions of the month.**

**Comment by yanavozniuk** [comment]
the same prob
