### ISSUE TITLE
Hide - Dashboard On Sheet Filter Controls

### ISSUE THREAD

**Issue by ktersius** [awslabs/amazon-quicksight-embedding-sdk#53]
What would be the correct way to hide the filtering controls as shown in the screenshot? It seems there are some ambiguity between parameter controls and other controls. 

Reading the [documentation](https://docs.aws.amazon.com/quicksight/latest/user/embedded-dashboards-functionality.html) it seems to indicate there should be a way to configure this?

> _To enable you to customize the dashboard with your app's theme, Amazon QuickSight hides the top navigation bar. When you publish a dashboard, you can also choose to hide the advanced filtering options and the **on-sheet filter controls**. That way, you can use controls that are embedded in your app instead. You can also pass in fragments by using the dashboard URL to further customize the view of the data._

But when you go to the publish option in Quicksight there are no options to hide the **on-sheet filter controls**.

![image](https://user-images.githubusercontent.com/6417718/90701180-de173700-e2db-11ea-816b-01cce36df7b2.png)

**Comment by ktersius** [comment]
Thank you. So just to summarise, hiding the Controls section is not supported only collapsing it and should you wish to not show any controls you need to delete all controls from the Analysis.

**Comment by JackieAnVal** [comment]
I think I had the same problem, 

Description: 
I had a Dashboard where I needed the data to be filtered by the user logged in my App. Since I could not manage to understand and implement the row level security:(  I did a work-around... ish 

Solution(NOTE: I had Enterprise Edition):
I made a parameter Control, where my parameter was Email. I tested the control and it worked, but then I did not want the users to be able to modify/use the Parameter Controls in the Embedded Dashboard, still I needed to use the parameters so I could filter the information depending on the user, so first I had to remove the control from the Controls 

![image](https://user-images.githubusercontent.com/45046537/119454170-dd458280-bcfd-11eb-964d-3a1066e7ba54.png)

Then I tested the parameters still worked, like so: 
1) When I publish my dashboard I unabled this options, Idk if it has some impact yet but here you go:

![image](https://user-images.githubusercontent.com/45046537/119454590-504ef900-bcfe-11eb-8988-b8cd053753bf.png)

2) After I published the dashboard I could see the info of ALL the users, so to test if my params still worked I used the URL of the dashboard and then added "#p.email=me@me.com", 

- the # is to indicate we are going to use some params in the following line
- The p. is for parameters
- Then the name of my parameter was Email, if you don't remember how you named your parameter you can go to your analysis, click on the parameter option, you should see something like this:
![image](https://user-images.githubusercontent.com/45046537/119455665-71641980-bcff-11eb-9634-01430f13fced.png) 

Complete example of how the URL should look like after I added "#p.email=me@me.com" : 
https://us-east-2.quicksight.aws.amazon.com/sn/dashboards/abc123-abc1-abc2-abc3-abcdefef1234#p.email=me@me.com

Click Enter and your info in the dashboard should change depending on the parameter you sent:) 

There are more options to send several parameters here-> https://docs.aws.amazon.com/quicksight/latest/user/parameters-in-a-url.html

If this worked, then when you are creating your EmbedDashboard you send the parameters: 
![image](https://user-images.githubusercontent.com/45046537/119456765-9e64fc00-bd00-11eb-983c-fe39f770a3ca.png)

I hope it was useful:) Have a great day!
