### ISSUE TITLE
Getting the following error. Our site is deployed AWS linux 2 appache server

### ISSUE THREAD

**Issue by irfanDC** [awslabs/amazon-quicksight-embedding-sdk#6]
Refused to display 'https://eu-west-1.quicksight.aws.amazon.com/sn/dashboards/1111111111111&punyCodeEmbedOrigin=https://abc.com/-#' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

**Comment by cxiangna** [comment]
Hi irfanDC,

1. The dashboard url you provided isn't a valid one. Please following the instructions here: https://docs.aws.amazon.com/en_us/quicksight/latest/user/embedding-dashboards.html
to get a valid embedded dashboard url by calling our public API.

2. Please also make sure you whitelist your domain following the steps in the instructions.

**Comment by dvillarraga** [comment]
1. Be sure you have your domain in the whitelist https://docs.aws.amazon.com/quicksight/latest/user/embedded-dashboards-with-iam-setup-step-1.html
2. You have to "get-dashboard-embed-url" from the same machine you are rendering your dashboard, e.g.: You can't get-dashboard-embed-url from your local machine and paste it on your server.

**Comment by PhatHoang21** [comment]
> 2. You have to "get-dashboard-embed-url" from the same machine you are rendering your dashboard, e.g.: You can't get-dashboard-embed-url from your local machine and paste it on your server.

@dvillarraga I called "get-dashboard-embed-url" from local machine.Then use ngrok.io for https and whitelist domain. I got same issue. Any idea?

**Comment by dvillarraga** [comment]
@PhatHoang21 mm, ngrok.io is new for me but looks that help you to expose httpd for incoming requests, not for requests you made. Be sure your "get-dashboard-embed-url" call, comes from your whitelist domain ( maybe if ngrok allows you ) and not from your ISP

**Comment by marcosoftinova** [comment]
> 1. Be sure you have your domain in the whitelist https://docs.aws.amazon.com/quicksight/latest/user/embedded-dashboards-with-iam-setup-step-1.html
> 2. You have to "get-dashboard-embed-url" from the same machine you are rendering your dashboard, e.g.: You can't get-dashboard-embed-url from your local machine and paste it on your server.

Thanks @dvillarraga, It was indeed lack of domain whitelisting.

In my case I was **instantiating** the **AWS.Quicksight** class with the **wrong region**. We have installed QuickSight on North Virginia (us-east-1) and that was our main Region. But our Dashboards were in Ohio (us-east-2).

**I did put our domain in whitelisting for Ohio**, but the SDK was set to use **North Virginia**, but in the last we had not created **neither dashboards nor domain whitelisting**. So, the problem was that the Dashboard was not being found and the domain was not whitelisted.

Changing the SDK region to the correct one (Ohio) fixed the problem.

A little piece of code (we are using lambdas -NodeJs- to generate Quicksight Signed URL):

`let quicksight = new AWS.QuickSight({
    region: CONSTANT.quickSightDirectoryRegion,
});`

(CONSTANT.quickSightDirectoryRegion === ''us-east-1")

Should be:
`let quicksight = new AWS.QuickSight({
	region: CONSTANT.quickSightDashboardRegion,
});`

(CONSTANT.quickSightDashboardRegion === "us-east-2")

**Comment by dongtong** [comment]
@dvillarraga My servers are in "us-west-2" and I got the embedded url by setting 'us-west-2'. BTW, I added whitelist, why it stills refused by quicksight service?

**Comment by dvillarraga** [comment]
@dongtong Please check: 

* https://docs.aws.amazon.com/en_us/quicksight/latest/user/embedding-dashboards.html 
* You are testing on the server directly, It probably won't work on your local environment.

If the issue persists, might you share more info about the code and issue you're experiencing?

**Comment by Krisslk** [comment]
@marcosoftinova  how did you find the quicksight dashboard region
